CAR-105 upgrade for using master branch in prod
meerkat-code/meerkat_auth pull request #67
Opened 2020-10-22 06:49 UTC by jsoppela

2020-10-23 08:02 UTC, jonathansberry approved these changes

2020-10-23 08:04 UTC, jonathansberry requested changes
Travis builds fail just for this commit in development.  Can you try to fix first?

2020-11-16 09:28 UTC, jsoppela commented
Local tests run correctly and Travis tests have been disabled due to their changed service model.

2020-11-17 08:20 UTC, jonathansberry approved these changes

2020-11-17 08:44 UTC, merged